ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_SAMPLE';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'SAMPLE_RECEIVED';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'RESULT_READY';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'SENT_TO_DOCTOR';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'NEEDS_CORRECTION';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED_TO_PATIENT';
ALTER TYPE "LabRequestStatus" ADD VALUE IF NOT EXISTS 'INVALID_SAMPLE';
